import type { CommunityComment, CommunityPostDetail, CommunityPostSummary } from '@/entities/community/api/communityApi'

export const mockCommunityPosts: CommunityPostDetail[] = [
  {
    postId: -201,
    userId: -21,
    authorNickname: '부산새벽산책',
    placeId: null,
    placeName: '부산광역시',
    category: 'TRAVEL_TIP',
    title: '해 뜨기 전부터 밤바다까지, 부산 하루 코스',
    content: '송정의 일출로 시작해 흰여울문화마을과 광안리 야경으로 마무리한 부산 하루 코스입니다.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=85',
    likeCount: 387,
    commentCount: 2,
    viewCount: 2148,
    createdAt: '2026-06-23T07:20:00',
    updatedAt: '2026-06-23T07:20:00',
    likedByMe: false,
    mine: false,
    cells: [
      {
        postCellId: null,
        sortOrder: 1,
        cellType: 'IMAGE',
        textContent: null,
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=85',
        alignment: 'CENTER',
      },
      {
        postCellId: null,
        sortOrder: 2,
        cellType: 'TEXT',
        textContent: '첫 차를 타고 송정해수욕장에 도착했어요. 해가 완전히 뜨기 전의 푸른 바다부터 천천히 밝아지는 수평선까지, 부산 여행의 시작으로 정말 좋았습니다.',
        imageUrl: null,
        alignment: 'LEFT',
        fontSizePx: 16,
      },
      {
        postCellId: null,
        sortOrder: 3,
        cellType: 'IMAGE',
        textContent: null,
        imageUrl: 'https://images.unsplash.com/photo-1499092346589-b9b6be3e94b2?auto=format&fit=crop&w=1400&q=85',
        alignment: 'CENTER',
      },
      {
        postCellId: null,
        sortOrder: 4,
        cellType: 'TEXT',
        textContent: '점심 뒤에는 흰여울문화마을의 바다 쪽 산책로를 걸었고, 저녁에는 광안리로 이동했습니다. 이동 동선이 단순해서 하루 일정인데도 급하게 느껴지지 않았어요. 편한 신발과 얇은 겉옷은 꼭 챙기세요.',
        imageUrl: null,
        alignment: 'LEFT',
        fontSizePx: 16,
      },
    ],
  },
  {
    postId: -202,
    userId: -22,
    authorNickname: '느린제주',
    placeId: null,
    placeName: '제주특별자치도',
    category: 'PLACE_REVIEW',
    title: '사람 적은 제주 숲길과 해안도로 2박 3일',
    content: '유명 카페 대신 숲길과 작은 포구를 중심으로 천천히 다녀온 제주 동쪽 여행 기록입니다.',
    imageUrl: 'https://images.unsplash.com/photo-1546874177-9e664107314e?auto=format&fit=crop&w=1400&q=85',
    likeCount: 296,
    commentCount: 2,
    viewCount: 1735,
    createdAt: '2026-06-22T18:40:00',
    updatedAt: '2026-06-22T18:40:00',
    likedByMe: false,
    mine: false,
    cells: [
      {
        postCellId: null,
        sortOrder: 1,
        cellType: 'TEXT',
        textContent: '이번 여행의 기준은 하나였습니다. 유명한 곳을 많이 찍기보다 한 장소에 오래 머물기. 첫날은 비자림 근처 숲길, 둘째 날은 동쪽 해안도로, 마지막 날은 작은 포구를 골랐어요.',
        imageUrl: null,
        alignment: 'LEFT',
        fontSizePx: 16,
      },
      {
        postCellId: null,
        sortOrder: 2,
        cellType: 'IMAGE',
        textContent: null,
        imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=85',
        alignment: 'CENTER',
      },
      {
        postCellId: null,
        sortOrder: 3,
        cellType: 'TEXT',
        textContent: '오전 9시 전에는 숲길이 조용하고 빛도 부드러웠습니다. 비가 조금 온 다음 날이라 흙냄새가 진했고, 천천히 왕복해도 두 시간이면 충분했어요.',
        imageUrl: null,
        alignment: 'LEFT',
        fontSizePx: 16,
      },
      {
        postCellId: null,
        sortOrder: 4,
        cellType: 'IMAGE',
        textContent: null,
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=85',
        alignment: 'CENTER',
      },
      {
        postCellId: null,
        sortOrder: 5,
        cellType: 'TEXT',
        textContent: '해안도로에서는 목적지를 자주 바꾸지 않는 편이 좋았습니다. 마음에 드는 포구가 보이면 잠깐 멈추고, 해 질 무렵까지 한 방향으로만 달리는 코스가 제주다운 여유를 가장 잘 느끼게 해줬어요.',
        imageUrl: null,
        alignment: 'LEFT',
        fontSizePx: 16,
      },
    ],
  },
]

export const mockCommunityComments: Record<number, CommunityComment[]> = {
  [-201]: [
    {
      commentId: -2011,
      postId: -201,
      commenterUserId: -31,
      authorNickname: '주말여행자',
      parentCommentId: null,
      replyToNickname: null,
      content: '새벽 송정부터 시작하는 동선이 정말 좋네요. 다음 부산 여행에 따라가 볼게요!',
      createdAt: '2026-06-23T09:10:00',
      updatedAt: '2026-06-23T09:10:00',
      mine: false,
      deleted: false,
      edited: false,
    },
    {
      commentId: -2012,
      postId: -201,
      commenterUserId: -32,
      authorNickname: '광안리밤바다',
      parentCommentId: null,
      replyToNickname: null,
      content: '하루 코스인데도 여유 있어 보여서 저장하고 싶어요.',
      createdAt: '2026-06-23T10:24:00',
      updatedAt: '2026-06-23T10:24:00',
      mine: false,
      deleted: false,
      edited: false,
    },
  ],
  [-202]: [
    {
      commentId: -2021,
      postId: -202,
      commenterUserId: -33,
      authorNickname: '숲길수집가',
      parentCommentId: null,
      replyToNickname: null,
      content: '관광지를 많이 돌지 않아도 충분히 좋은 여행이 된다는 게 느껴져요.',
      createdAt: '2026-06-22T20:05:00',
      updatedAt: '2026-06-22T20:05:00',
      mine: false,
      deleted: false,
      edited: false,
    },
    {
      commentId: -2022,
      postId: -202,
      commenterUserId: -34,
      authorNickname: '제주한달살이',
      parentCommentId: null,
      replyToNickname: null,
      content: '비 온 다음 날 숲길 추천, 완전 공감합니다.',
      createdAt: '2026-06-22T21:17:00',
      updatedAt: '2026-06-22T21:17:00',
      mine: false,
      deleted: false,
      edited: false,
    },
  ],
}

export function findMockCommunityPost(postId: number | null | undefined) {
  return mockCommunityPosts.find((post) => post.postId === postId) ?? null
}

export function toMockCommunitySummary(post: CommunityPostDetail): CommunityPostSummary {
  return {
    ...post,
    excerpt: post.content ? post.content.replace(/\s+/g, ' ').slice(0, 100) : null,
  }
}
